name: skyline
dependencies:
- backports_abc=0.4=py27_0
- beautifulsoup4=4.4.1=py27_0
- cffi=1.2.1=py27_0
- cryptography=1.0.2=py27_0
- decorator=4.0.4=py27_0
- enum34=1.1.1=py27_0
- flask=0.10.1=py27_1
- freetype=2.5.5=0
- funcsigs=0.4=py27_0
- gevent=1.0.1=py27_0
- greenlet=0.4.9=py27_0
- idna=2.0=py27_0
- ipaddress=1.0.14=py27_0
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_0
- jpeg=8d=0
- libffi=3.0.13=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.4.4=py27_0
- mako=1.0.3=py27_0
- markupsafe=0.23=py27_0
- mock=1.3.0=py27_0
- mysql-python=1.2.5=py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=3
- openssl=1.0.2e=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pbr=1.3.0=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.0.0=py27_1
- pip=7.1.2=py27_0
- py=1.4.30=py27_0
- pyasn1=0.1.9=py27_0
- pycparser=2.14=py27_0
- pyopenssl=0.15.1=py27_1
- pytest=2.8.1=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- readline=6.2=2
- redis-py=2.10.3=py27_0
- requests=2.8.1=py27_0
- scikit-image=0.11.3=np110py27_0
- scipy=0.16.0=np110py27_1
- setuptools=19.2=py27_0
- simplegeneric=0.8.1=py27_0
- simplejson=3.8.0=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlalchemy=1.0.9=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.0.0=py27_0
- werkzeug=0.11.2=py27_0
- wheel=0.26.0=py27_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - amqp==1.4.7
  - anyjson==0.3.3
  - apns-client==0.2.1
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - beaker==1.7.0
  - billiard==3.3.0.21
  - blinker==1.4
  - boto3==1.2.2
  - botocore==1.3.9
  - byteplay==0.2
  - celery==3.1.19
  - certifi==2015.11.20.1
  - characteristic==14.3.0
  - dbutils==1.1
  - docutils==0.12
  - elasticsearch==2.1.0
  - elasticsearch-dsl==0.0.9
  - flask-mako==0.3
  - flask-wtf==0.12
  - futures==2.2.0
  - ipython-genutils==0.1.0
  - jieba==0.37
  - jmespath==0.9.0
  - jsonschema==2.3.0
  - kombu==3.0.30
  - libmc==0.5.6
  - mmseg==1.3.0
  - paste==2.0.2
  - pivottablejs==0.1.0
  - git+https://github.com/xiachufang/pyapns.git@v50
  - pyasn1-modules==0.0.8
  - python-epoll==1.0
  - pytest-mock==0.9.0
  - qiniu==7.0.5
  - raven==5.8.1
  - redis==2.10.3
  - rsa==3.2.3
  - service-identity==14.0.0
  - twisted==15.5.0
  - ua-parser==0.5.1
  - urllib3==1.12
  - uwsgi==2.0.12
  - wtforms==2.1
  - xlrd==0.9.4
  - xlsxwriter==0.7.7
  - xlwt==1.0.0
  - xmltodict==0.9.2
  - zope.interface==4.1.3
  - statsd==3.2.1
  - pyzmq==15.2.0
